/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tr.edu.medipol.ogrenciler.yucelozalp.odev1;

import javax.swing.JOptionPane;

/**
 *
 * @author yucel.ozalp
 */
public class ArabaForm extends javax.swing.JFrame {

	/**
	 * Creates new form testForm
	 */
	public ArabaForm() {
		setTitle("Yücel Rent A Car ");
		initComponents();

		Araba bmw = new Araba("BMW", "i525", "Beyaz", 2017, "Benzin", 10000000);
		Araba audi = new Araba("Audi", "A4", "Siyah", 2017, "Dizel", 20000000);
		Araba volvo = new Araba("Volvo", "S40", "Mavi", 2017, "Dizel", 2500000);
		Araba as = new Araba("Aston Martin", "DB7", "Mavi", 2017, "Dizel", 2500000);
		Araba bentley = new Araba("Bentley", "Arnage", "Mavi", 2017, "Dizel", 2500000);
		Araba cadillac = new Araba("Cadillac", "BLS", "Mavi", 2017, "Dizel", 2500000);
		Araba chevrolet = new Araba("Chevrolet", "Camaro", "Mavi", 2017, "Dizel", 2500000);
		Araba chrysler = new Araba("Chrysler", "300 C", "Mavi", 2017, "Dizel", 2500000);
		Araba ferrari = new Araba("Ferrari", "360", "Mavi", 2017, "Dizel", 2500000);
		Araba avenger = new Araba("Dodge", "Avenger", "Mavi", 2017, "Dizel", 2500000);

		String[] arabalars = new String[] { bmw.Marka, audi.Marka, volvo.Marka, as.Marka, bentley.Marka, cadillac.Marka,
				chevrolet.Marka, chrysler.Marka, ferrari.Marka, avenger.Marka };
		// bmw.Marka,audi.Marka,volvo.Marka,as.Marka,bentley.Marka,cadillac.Marka,chevrolet.Marka,chrysler.Marka,ferrari.Marka,avenger.Marka

		for (int i = 0; i < arabalars.length; i++) {
			System.out.println("Araba: " + arabalars[i]);
			jComboBox1.addItem(arabalars[i]);
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox<>();
		jButton1 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Proxima Nova Cn Rg", 0, 18)); // NOI18N
		jLabel1.setText("Yücel Rent a Car");

		jLabel2.setText("Firmamızda şuanda aşağıda bulunan araçlar mevcuttur.");

		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});

		jButton1.setText("Gönder");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel3.setText("jLabel3");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(29, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(28, 28, 28))
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(105, 105, 105).addComponent(jLabel1))
								.addGroup(layout.createSequentialGroup().addGap(123, 123, 123)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jButton1).addGroup(layout.createSequentialGroup()
														.addGap(13, 13, 13).addComponent(jLabel3)))))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(25, 25, 25).addComponent(jLabel1).addGap(28, 28, 28)
						.addComponent(jLabel2).addGap(31, 31, 31)
						.addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(32, 32, 32).addComponent(jLabel3).addGap(79, 79, 79).addComponent(jButton1)
						.addContainerGap(191, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
		// TODO add your handling code here:
		jLabel3.setText(String.valueOf(jComboBox1.getSelectedItem()));
		System.out.println("Combo changed");
	}// GEN-LAST:event_jComboBox1ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		String st = "Test AlertBox Kontrol";
		JOptionPane.showMessageDialog(null, st);

	}// GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ArabaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ArabaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ArabaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ArabaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ArabaForm().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	// End of variables declaration//GEN-END:variables
}
